# Generated by Django 5.2.6 on 2025-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_audiorecording_chatmessage_prescription_record_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiorecording",
            old_name="sent_at",
            new_name="recorded_at",
        ),
        migrations.RemoveField(
            model_name="record",
            name="description",
        ),
        migrations.AddField(
            model_name="audiorecording",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="audiorecording",
            name="title",
            field=models.CharField(default="Recording", max_length=200),
        ),
        migrations.AddField(
            model_name="audiorecording",
            name="uploaded_by",
            field=models.CharField(default="doctor", max_length=10),
        ),
        migrations.AddField(
            model_name="record",
            name="title",
            field=models.CharField(default="Record", max_length=200),
        ),
        migrations.AddField(
            model_name="record",
            name="type",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="record",
            name="uploaded_by",
            field=models.CharField(default="doctor", max_length=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="records/"),
        ),
    ]
