# Generated by Django 5.2.6 on 2025-09-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_sent_at_audiorecording_recorded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
