# Generated by Django 5.2.6 on 2025-09-13 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="duration_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.CreateModel(
            name="MedicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                ("scheduled_time", models.DateTimeField()),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_logs",
                        to="accounts.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_time"],
            },
        ),
    ]
