# Generated by Django 5.2.6 on 2025-09-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_prescription_duration_days_medicationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
