# Generated by Django 5.2.6 on 2025-09-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_prescription_last_reminder_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TakenDose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                ("taken_at", models.DateTimeField()),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken_doses",
                        to="accounts.prescription",
                    ),
                ),
            ],
            options={
                "unique_together": {("prescription", "medicine_name", "taken_at")},
            },
        ),
        migrations.DeleteModel(
            name="MedicationLog",
        ),
    ]
