# Generated by Django 5.2.6 on 2025-09-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_takendose_delete_medicationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                ("scheduled_time", models.DateTimeField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="accounts.prescription",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("prescription", "medicine_name", "scheduled_time")
                },
            },
        ),
    ]
