from django.urls import path
from .views import (
    SignupView,
    LoginView,
    DoctorPatientsView,
    PatientRecordsView,
    PatientAudioRecordingsView,
    PatientChatView,
    PatientPrescriptionsView,
    DoctorProfileView,
    PatientDashboardDataView,
    PatientRecordsManageView,
    PatientAudioManageView,
    PatientChatManageView,
    PatientPrescriptionsViewPublic,
    PatientDoctorsView,
    PatientAppointmentsView,
    DoctorAppointmentsView,
    PatientMedicationLogsView,
    PatientAIChatView,
    DoctorSendPrescriptionsSMSView,
    RequestPasswordResetView,
    VerifyOTPView,
    ResetPasswordView,
)
from .views import LogoutView

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('doctor/patients/', DoctorPatientsView.as_view(), name='doctor_patients'),
    path('doctor/patients/<int:patient_id>/records/', PatientRecordsView.as_view(), name='patient_records'),
    path('doctor/patients/<int:patient_id>/audio/', PatientAudioRecordingsView.as_view(), name='patient_audio'),
    path('doctor/patients/<int:patient_id>/chat/', PatientChatView.as_view(), name='patient_chat'),
    path('doctor/patients/<int:patient_id>/prescriptions/', PatientPrescriptionsView.as_view(), name='patient_prescriptions'),
    path('doctor/profile/', DoctorProfileView.as_view(), name='doctor_profile'),
    # Patient self-service endpoints
    path('patient/dashboard/', PatientDashboardDataView.as_view(), name='patient_dashboard_data'),
    path('patient/records/', PatientRecordsManageView.as_view(), name='patient_records_manage'),
    path('patient/audio/', PatientAudioManageView.as_view(), name='patient_audio_manage'),
    path('patient/chat/', PatientChatManageView.as_view(), name='patient_chat_manage'),
    path('patient/prescriptions/', PatientPrescriptionsViewPublic.as_view(), name='patient_prescriptions_public'),
    path('patient/doctors/', PatientDoctorsView.as_view(), name='patient_doctors'),
    path('patient/ai-chat/', PatientAIChatView.as_view(), name='patient_ai_chat'),
    path('patient/appointments/', PatientAppointmentsView.as_view(), name='patient_appointments'),
    path('doctor/appointments/', DoctorAppointmentsView.as_view(), name='doctor_appointments'),
    path('doctor/appointments/<int:appointment_id>/', DoctorAppointmentsView.as_view(), name='doctor_appointment_detail'),
    path('patient/medication-logs/', PatientMedicationLogsView.as_view(), name='patient_medication_logs'),
    path('doctor/patients/<int:patient_id>/prescriptions/send-sms/', DoctorSendPrescriptionsSMSView.as_view(), name='doctor_send_prescriptions_sms'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # Password reset endpoints
    path('password-reset/request/', RequestPasswordResetView.as_view(), name='password_reset_request'),
    path('password-reset/verify/', VerifyOTPView.as_view(), name='password_reset_verify'),
    path('password-reset/confirm/', ResetPasswordView.as_view(), name='password_reset_confirm'),
]
